var searchData=
[
  ['takeover_0',['TakeOver',['../class_ticketing_application_a_p_i_1_1_controllers_1_1_ticket_controller.html#a32e90409b8d474e1d70fdd500da54815',1,'TicketingApplicationAPI::Controllers::TicketController']]],
  ['ticket_1',['Ticket',['../class_ticketing_application_a_p_i_1_1_models_1_1_ticket.html',1,'TicketingApplicationAPI::Models']]],
  ['ticket_2ecs_2',['Ticket.cs',['../_ticket_8cs.html',1,'']]],
  ['ticketcontroller_3',['TicketController',['../class_ticketing_application_a_p_i_1_1_controllers_1_1_ticket_controller.html',1,'TicketingApplicationAPI.Controllers.TicketController'],['../class_ticketing_application_a_p_i_1_1_controllers_1_1_ticket_controller.html#a7a0fff0e2f209caa24fe41261f52fc5e',1,'TicketingApplicationAPI.Controllers.TicketController.TicketController()']]],
  ['ticketcontroller_2ecs_4',['TicketController.cs',['../_ticket_controller_8cs.html',1,'']]],
  ['ticketid_5',['TicketID',['../class_ticketing_application_a_p_i_1_1_models_1_1_ticket.html#a3e78c857155d43860d028c56a3659874',1,'TicketingApplicationAPI::Models::Ticket']]],
  ['ticketingapplicationapi_6',['TicketingApplicationAPI',['../namespace_ticketing_application_a_p_i.html',1,'']]],
  ['ticketingapplicationapi_2eassemblyinfo_2ecs_7',['TicketingApplicationAPI.AssemblyInfo.cs',['../_ticketing_application_a_p_i_8_assembly_info_8cs.html',1,'']]],
  ['ticketingapplicationapi_2eglobalusings_2eg_2ecs_8',['TicketingApplicationAPI.GlobalUsings.g.cs',['../_ticketing_application_a_p_i_8_global_usings_8g_8cs.html',1,'']]],
  ['ticketingapplicationapi_2emvcapplicationpartsassemblyinfo_2ecs_9',['TicketingApplicationAPI.MvcApplicationPartsAssemblyInfo.cs',['../_ticketing_application_a_p_i_8_mvc_application_parts_assembly_info_8cs.html',1,'']]],
  ['ticketingapplicationapi_3a_3acontext_10',['Context',['../namespace_ticketing_application_a_p_i_1_1_context.html',1,'TicketingApplicationAPI']]],
  ['ticketingapplicationapi_3a_3acontrollers_11',['Controllers',['../namespace_ticketing_application_a_p_i_1_1_controllers.html',1,'TicketingApplicationAPI']]],
  ['ticketingapplicationapi_3a_3amigrations_12',['Migrations',['../namespace_ticketing_application_a_p_i_1_1_migrations.html',1,'TicketingApplicationAPI']]],
  ['ticketingapplicationapi_3a_3amodels_13',['Models',['../namespace_ticketing_application_a_p_i_1_1_models.html',1,'TicketingApplicationAPI']]],
  ['tickets_14',['Tickets',['../class_ticketing_application_a_p_i_1_1_context_1_1_app_db_context.html#a9e23dc0904dda8d49da7f57d0d0ab681',1,'TicketingApplicationAPI::Context::AppDbContext']]],
  ['token_15',['Token',['../class_ticketing_application_a_p_i_1_1_models_1_1_user.html#a683ee3355674d9e9f193ee6821b036a1',1,'TicketingApplicationAPI::Models::User']]]
];
